# Generated by Django 5.1.15 on 2026-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_processed_events",
            },
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="last_stripe_event_created",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
