# Generated by Django 6.0.1 on 2026-01-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingprofile",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
