# Generated by Django 5.1.15 on 2026-02-16 02:33

from django.db import migrations, models


def convert_empty_to_null(apps, schema_editor):
    """Convert empty string values to NULL before adding unique constraint."""
    BillingProfile = apps.get_model("billing", "BillingProfile")
    BillingProfile.objects.filter(stripe_customer_id="").update(
        stripe_customer_id=None
    )
    BillingProfile.objects.filter(stripe_subscription_id="").update(
        stripe_subscription_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_processedevent_and_more"),
    ]

    operations = [
        # Step 1: Allow NULL (without unique yet)
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Step 2: Convert empty strings to NULL
        migrations.RunPython(
            convert_empty_to_null,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
