# Generated by Django 5.1.15 on 2026-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_stripe_ids_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
