# Generated by Django 5.1.15 on 2026-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_billingprofile_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
