#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# create_ui_upgrade_pr.sh
#
# Creates a Git branch, commits UI upgrade compatibility changes,
# pushes the branch, and prints a ready-to-use PR title/body.
#
# Purpose:
#   Standardize the PR creation step after:
#   - ui/ directory update
#   - impact analysis
#   - minimal fixes
#   - manual verification
#
# Requirements:
#   - Run from project root
#   - git configured
#   - remote "origin" configured
#
# Optional:
#   - gh CLI installed and authenticated
#     If available, the script can create the PR automatically.
#
# Usage:
#   ./scripts/create_ui_upgrade_pr.sh
#   ./scripts/create_ui_upgrade_pr.sh v1.2.0
#   ./scripts/create_ui_upgrade_pr.sh v1.2.0 "Fix customers list after UI update"
#
# Examples:
#   ./scripts/create_ui_upgrade_pr.sh
#   ./scripts/create_ui_upgrade_pr.sh v1.2.0
#   ./scripts/create_ui_upgrade_pr.sh v1.2.0 "Update template compatibility for Sekai UI System v1.2.0"
# ============================================================

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/ui-upgrade-report"
DEFAULT_VERSION="unknown"
UI_VERSION="${1:-$DEFAULT_VERSION}"
COMMIT_MSG_INPUT="${2:-}"

cd "$PROJECT_ROOT"

timestamp="$(date +%Y%m%d-%H%M%S)"
safe_version="$(echo "$UI_VERSION" | tr '/' '-' | tr ' ' '-' )"
BRANCH_NAME="chore/ui-upgrade-${safe_version}-${timestamp}"

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "ERROR: This is not a git repository." >&2
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Detected working tree changes."
else
  echo "No changes detected. Nothing to commit."
  exit 1
fi

if [[ -z "$COMMIT_MSG_INPUT" ]]; then
  if [[ "$UI_VERSION" == "$DEFAULT_VERSION" ]]; then
    COMMIT_MSG="Update UI system compatibility"
  else
    COMMIT_MSG="Update UI system compatibility for ${UI_VERSION}"
  fi
else
  COMMIT_MSG="$COMMIT_MSG_INPUT"
fi

PR_TITLE="$COMMIT_MSG"

PR_BODY_FILE="$REPORT_DIR/ui_upgrade_pr_body.md"
mkdir -p "$REPORT_DIR"

cat > "$PR_BODY_FILE" <<EOF
# UI Upgrade PR

## Summary

This PR applies SaaS Template compatibility updates after a Sekai UI System refresh.

## Included work

- updated \`ui/\` directory
- impact analysis completed
- minimal compatibility fixes applied
- manual verification completed

## Review checklist

- [ ] sidebar renders correctly
- [ ] topbar renders correctly
- [ ] tables render correctly
- [ ] pagination works
- [ ] forms render correctly
- [ ] no TemplateSyntaxError
- [ ] no NoReverseMatch
- [ ] no missing template context variables

## Notes

UI version: \`${UI_VERSION}\`

Generated by:

\`scripts/create_ui_upgrade_pr.sh\`
EOF

echo "Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

echo "Staging changes..."
git add .

echo "Creating commit..."
git commit -m "$COMMIT_MSG"

echo "Pushing branch..."
git push -u origin "$BRANCH_NAME"

echo
echo "========================================"
echo "PR preparation complete"
echo "========================================"
echo "Branch: $BRANCH_NAME"
echo "Commit: $COMMIT_MSG"
echo
echo "Suggested PR title:"
echo "$PR_TITLE"
echo
echo "PR body file:"
echo "$PR_BODY_FILE"
echo

if command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI detected."
  echo
  echo "You can create the PR automatically with:"
  echo "gh pr create --title \"$PR_TITLE\" --body-file \"$PR_BODY_FILE\" --base main --head \"$BRANCH_NAME\""
  echo
  read -r -p "Create PR now with gh? [y/N]: " create_now
  if [[ "${create_now:-N}" =~ ^[Yy]$ ]]; then
    gh pr create --title "$PR_TITLE" --body-file "$PR_BODY_FILE" --base main --head "$BRANCH_NAME"
  fi
else
  echo "GitHub CLI not found."
  echo "Create the PR manually using:"
  echo
  echo "Title:"
  echo "  $PR_TITLE"
  echo
  echo "Body file:"
  echo "  $PR_BODY_FILE"
fi
